//
//  Constants.swift
//  PMA
//
//  Created by HadisehSafaei on 5/18/1402 AP.
//

import Foundation

public enum Currency: Int {
    
    case KYD
    case JPY
    case SOS
    case CAD
    case HN
    case FJD
    case MZN
    case MDL
    case QAR
    case UGX
    case IRR
    case STN
    case UAH
    case KRW
    case CDF
    case SYP
    case TVD
    case CHF
    case CUP
    case KID
    case TZS
    case TOP
    case XPF
    case CLP
    case PGK
    case EUR
    case NIO
    case ANG
    case ERN
    case NGN
    case BMD
    case KES
    case NAD
    case CRC
    case AWG
    case PYG
    case MMK
    case SRD
    case BGN
    case MWK
    case BYN
    case BZD
    case LKR
    case AZN
    case PHP
    case SDG
    case HUF
    case UZS
    case GIP
    case XCD
    case TJS
    case MYR
    case GMD
    case LAK
    case CZK
    case PKR
    case PAB
    case BAM
    case ISK
    case GHS
    case TTD
    case BND
    case YER
    case PLN
    case XOF
    case AFN
    case IMP
    case LSL
    case MRU
    case SHP
    case AED
    case DJF
    case GNF
    case VND
    case ILS
    case WST
    case BDT
    case LBP
    case KMF
    case ZWL
    case RSD
    case GTQ
    case SZL
    case TWD
    case XAF
    case ZAR
    case SCR
    case AUD
    case BTN
    case DOP
    case ETB
    case LRD
    case GEL
    case FOK
    case DKK
    case BBD
    case NPR
    case BOB
    case BHD
    case AOA
    case SSP
    case BIF
    case AMD
    case BWP
    case ALL
    case KHR
    case GGP
    case IDR
    case RON
    case SAR
    case JOD
    case SGD
    case JEP
    case KZT
    case XDR
    case CNY
    case SBD
    case NZD
    case BRL
    case OMR
    case MOP
    case CVE
    case RUB
    case KWD
    case GBP
    case LYD
    case MKD
    case NOK
    case JMD
    case COP
    case DZD
    case ARS
    case HRK
    case SEK
    case TND
    case IQD
    case HKD
    case MVR
    case MAD
    case PEN
    case EGP
    case TMT
    case SLE
    case BSD
    case VUV
    case GYD
    case VES
    case UYU
    case TRY
    case HTG
    case USD
    case FKP
    case KGS
    case MNT
    case THB
    case RWF
    case MXN
    case MGA
    case MUR
    case ZMW
    case SLL
    case INR
    
    var name : String {
        switch self {
        case .KYD:
            return "KYD"
        case .JPY:
            return "JPY"
        case .SOS:
            return "SOS"
        case .CAD:
            return "CAD"
        case .HN:
            return "HN"
        case .FJD:
            return "FJD"
        case .MZN:
            return "MZN"
        case .MDL:
            return "MDL"
        case .QAR:
            return "QAR"
        case .UGX:
            return "UGX"
        case .IRR:
            return "IRR"
        case .STN:
            return "STN"
        case .UAH:
            return "UAH"
        case .KRW:
            return "KRW"
        case .CDF:
            return "CDF"
        case .SYP:
            return "SYP"
        case .TVD:
            return "TVD"
        case .CHF:
            return "CHF"
        case .CUP:
            return "CUP"
        case .KID:
            return "KID"
        case .TZS:
            return "TZS"
        case .TOP:
            return "TOP"
        case .XPF:
            return "XPF"
        case .CLP:
            return "CLP"
        case .PGK:
            return "PGK"
        case .EUR:
            return "EUR"
        case .NIO:
            return "NIO"
        case .ANG:
            return "ANG"
        case .ERN:
            return "ERN"
        case .NGN:
            return "NGN"
        case .BMD:
            return "BMD"
        case .KES:
            return "KES"
        case .NAD:
            return "NAD"
        case .CRC:
            return "CRC"
        case .AWG:
            return "AWG"
        case .PYG:
            return "PYG"
        case .MMK:
            return "MMK"
        case .SRD:
            return "SRD"
        case .BGN:
            return "BGN"
        case .MWK:
            return "MWK"
        case .BYN:
            return "BYN"
        case .BZD:
            return "BZD"
        case .LKR:
            return "LKR"
        case .AZN:
            return "AZN"
        case .PHP:
            return "PHP"
        case .SDG:
            return "SDG"
        case .HUF:
            return "HUF"
        case .UZS:
            return "UZS"
        case .GIP:
            return "GIP"
        case .XCD:
            return "XCD"
        case .TJS:
            return "TJS"
        case .MYR:
            return "MYR"
        case .GMD:
            return "GMD"
        case .LAK:
            return "LAK"
        case .CZK:
            return "CZK"
        case .PKR:
            return "PKR"
        case .PAB:
            return "PAB"
        case .BAM:
            return "BAM"
        case .ISK:
            return "ISK"
        case .GHS:
            return "GHS"
        case .TTD:
            return "TTD"
        case .BND:
            return "BND"
        case .YER:
            return "YER"
        case .PLN:
            return "PLN"
        case .XOF:
            return "XOF"
        case .AFN:
            return "AFN"
        case .IMP:
            return "IMP"
        case .LSL:
            return "LSL"
        case .MRU:
            return "MRU"
        case .SHP:
            return "SHP"
        case .AED:
            return "AED"
        case .DJF:
            return "DJF"
        case .GNF:
            return "GNF"
        case .VND:
            return "VND"
        case .ILS:
            return "ILS"
        case .WST:
            return "WST"
        case .BDT:
            return "BDT"
        case .LBP:
            return "LBP"
        case .KMF:
            return "KMF"
        case .ZWL:
            return "ZWL"
        case .RSD:
            return "RSD"
        case .GTQ:
            return "GTQ"
        case .SZL:
            return "SZL"
        case .TWD:
            return "TWD"
        case .XAF:
            return "XAF"
        case .ZAR:
            return "ZAR"
        case .SCR:
            return "SCR"
        case .AUD:
            return "AUD"
        case .BTN:
            return "BTN"
        case .DOP:
            return "DOP"
        case .ETB:
            return "ETB"
        case .LRD:
            return "LRD"
        case .GEL:
            return "GEL"
        case .FOK:
            return "FOK"
        case .DKK:
            return "DKK"
        case .BBD:
            return "BBD"
        case .NPR:
            return "NPR"
        case .BOB:
            return "BOB"
        case .BHD:
            return "BHD"
        case .AOA:
            return "AOA"
        case .SSP:
            return "SSP"
        case .BIF:
            return "BIF"
        case .AMD:
            return "AMD"
        case .BWP:
            return "BWP"
        case .ALL:
            return "ALL"
        case .KHR:
            return "KHR"
        case .GGP:
            return "GGP"
        case .IDR:
            return "IDR"
        case .RON:
            return "RON"
        case .SAR:
            return "SAR"
        case .JOD:
            return "JOD"
        case .SGD:
            return "SGD"
        case .JEP:
            return "JEP"
        case .KZT:
            return "KZT"
        case .XDR:
            return "XDR"
        case .CNY:
            return "CNY"
        case .SBD:
            return "SBD"
        case .NZD:
            return "NZD"
        case .BRL:
            return "BRL"
        case .OMR:
            return "OMR"
        case .MOP:
            return "MOP"
        case .CVE:
            return "CVE"
        case .RUB:
            return "RUB"
        case .KWD:
            return "KWD"
        case .GBP:
            return "GBP"
        case .LYD:
            return "LYD"
        case .MKD:
            return "MKD"
        case .NOK:
            return "NOK"
        case .JMD:
            return "JMD"
        case .COP:
            return "COP"
        case .DZD:
            return "DZD"
        case .ARS:
            return "ARS"
        case .HRK:
            return "HRK"
        case .SEK:
            return "SEK"
        case .TND:
            return "TND"
        case .IQD:
            return "IQD"
        case .HKD:
            return "HKD"
        case .MVR:
            return "MVR"
        case .MAD:
            return "MAD"
        case .PEN:
            return "PEN"
        case .EGP:
            return "EGP"
        case .TMT:
            return "TMT"
        case .SLE:
            return "SLE"
        case .BSD:
            return "BSD"
        case .VUV:
            return "VUV"
        case .GYD:
            return "GYD"
        case .VES:
            return "VES"
        case .UYU:
            return "UYU"
        case .TRY:
            return "TRY"
        case .HTG:
            return "HTG"
        case .USD:
            return "USD"
        case .FKP:
            return "FKP"
        case .KGS:
            return "KGS"
        case .MNT:
            return "MNT"
        case .THB:
            return "THB"
        case .RWF:
            return "RWF"
        case .MXN:
            return "MXN"
        case .MGA:
            return "MGA"
        case .MUR:
            return "MUR"
        case .ZMW:
            return "ZMW"
        case .SLL:
            return "SLL"
        case .INR:
            return "INR"
        }
    }
    
    
    var countryName : String {
        switch self {
            
        case .KYD:
            return "Cayman Islands"
        case .JPY:
            return "Japan"
        case .SOS:
            return "Somalia"
        case .CAD:
            return "Canada"
        case .HN:
            return "Honduras"
        case .FJD:
            return "Fiji"
        case .MZN:
            return "Mozambique"
        case .MDL:
            return "Moldova"
        case .QAR:
            return "Qatar"
        case .UGX:
            return "Uganda"
        case .IRR:
            return "Iran"
        case .STN:
            return "São Tomé and Príncipe"
        case .UAH:
            return "Ukraine"
        case .KRW:
            return "Korea South"
        case .CDF:
            return "Congo"
        case .SYP:
            return "Syria"
        case .TVD:
            return "Country"
        case .CHF:
            return "Liechtenstein"
        case .CUP:
            return "Cuba"
        case .KID:
            return "Country"
        case .TZS:
            return "Tanzania"
        case .TOP:
            return "Tonga"
        case .XPF:
            return "French Polynesia"
        case .CLP:
            return "Chile"
        case .PGK:
            return "Papua New Guinea"
        case .EUR:
            return "Andorra"
        case .NIO:
            return "Nicaragua"
        case .ANG:
            return "Curaçao"
        case .ERN:
            return "Eritrea"
        case .NGN:
            return "Nigeria"
        case .BMD:
            return "Bermuda"
        case .KES:
            return "Kenya"
        case .NAD:
            return "Namibia"
        case .CRC:
            return "Costa Rica"
        case .AWG:
            return "Aruba"
        case .PYG:
            return "Paraguay"
        case .MMK:
            return "Myanmar"
        case .SRD:
            return "Suriname"
        case .BGN:
            return "Bulgaria"
        case .MWK:
            return "Malawi"
        case .BYN:
            return "Belarus"
        case .BZD:
            return "Belize"
        case .LKR:
            return "Sri Lanka"
        case .AZN:
            return "Azerbaijan"
        case .PHP:
            return "Philippines"
        case .SDG:
            return "Sudan"
        case .HUF:
            return "Hungary"
        case .UZS:
            return "Uzbekistan"
        case .GIP:
            return "Gibraltar"
        case .XCD:
            return "Anguilla"
        case .TJS:
            return "Tajikistan"
        case .MYR:
            return "Malaysia"
        case .GMD:
            return "Gambia"
        case .LAK:
            return "Laos"
        case .CZK:
            return "Czech Republic"
        case .PKR:
            return "Pakistan"
        case .PAB:
            return "Panama"
        case .BAM:
            return "Bosnia"
        case .ISK:
            return "Iceland"
        case .GHS:
            return "Ghana"
        case .TTD:
            return "Trinidad and Tobago"
        case .BND:
            return "Brunei"
        case .YER:
            return "Yemen"
        case .PLN:
            return "Poland"
        case .XOF:
            return "Benin"
        case .AFN:
            return "Afghanistan"
        case .IMP:
            return "Country"
        case .LSL:
            return "Lesotho"
        case .MRU:
            return "Mauritania"
        case .SHP:
            return "Ascension Island"
        case .AED:
            return "United Arab Emirates"
        case .DJF:
            return "Djibouti"
        case .GNF:
            return "Guinea"
        case .VND:
            return "Vietnam"
        case .ILS:
            return "Israel"
        case .WST:
            return "Samoa"
        case .BDT:
            return "Bangladesh"
        case .LBP:
            return "Lebanon"
        case .KMF:
            return "Comoros"
        case .ZWL:
            return "Country"
        case .RSD:
            return "Serbia"
        case .GTQ:
            return "Guatemala"
        case .SZL:
            return "Eswatini"
        case .TWD:
            return "Republic of China"
        case .XAF:
            return "Congo"
        case .ZAR:
            return "Eswatini"
        case .SCR:
            return "Seychelles"
        case .AUD:
            return "Australia"
        case .BTN:
            return "Bhutan"
        case .DOP:
            return "Dominican Republic"
        case .ETB:
            return "Ethiopia"
        case .LRD:
            return "Liberia"
        case .GEL:
            return "Georgia"
        case .FOK:
            return "Country"
        case .DKK:
            return "Denmark"
        case .BBD:
            return "Barbados"
        case .NPR:
            return "Nepal"
        case .BOB:
            return "Bolivia"
        case .BHD:
            return "Bahrain"
        case .AOA:
            return "Angola"
        case .SSP:
            return "South Sudan"
        case .BIF:
            return "Burundi"
        case .AMD:
            return "Armenia"
        case .BWP:
            return "Botswana"
        case .ALL:
            return "Albania"
        case .KHR:
            return "Cambodia"
        case .GGP:
            return "Country"
        case .IDR:
            return "Indonesia"
        case .RON:
            return "Romania"
        case .SAR:
            return "Saudi Arabia"
        case .JOD:
            return "Jordan"
        case .SGD:
            return "Brunei"
        case .JEP:
            return "Country"
        case .KZT:
            return "Kazakhstan"
        case .XDR:
            return "Country"
        case .CNY:
            return "China"
        case .SBD:
            return "Solomon Islands"
        case .NZD:
            return "Cook Islands"
        case .BRL:
            return "Brazil"
        case .OMR:
            return "Oman"
        case .MOP:
            return "Macau"
        case .CVE:
            return "Cape Verde"
        case .RUB:
            return "Abkhazia"
        case .KWD:
            return "Kuwait"
        case .GBP:
            return "Falkland Islands"
        case .LYD:
            return "Libya"
        case .MKD:
            return "North Macedonia"
        case .NOK:
            return "Norway"
        case .JMD:
            return "Jamaica"
        case .COP:
            return "Colombia"
        case .DZD:
            return "Algeria"
        case .ARS:
            return "Argentina"
        case .HRK:
            return "Country"
        case .SEK:
            return "Sweden"
        case .TND:
            return "Tunisia"
        case .IQD:
            return "Iraq"
        case .HKD:
            return "Hong Kong"
        case .MVR:
            return "Maldives"
        case .MAD:
            return "Morocco"
        case .PEN:
            return "Ascension Island"
        case .EGP:
            return "Egypt"
        case .TMT:
            return "Turkmenistan"
        case .SLE:
            return "Sierra Leone"
        case .BSD:
            return "Bahamas"
        case .VUV:
            return "Vanuatu"
        case .GYD:
            return "Guyana"
        case .VES:
            return "Venezuela"
        case .UYU:
            return "Uruguay"
        case .TRY:
            return "Northern Cyprus"
        case .HTG:
            return "Haiti"
        case .USD:
            return "Bonaire"
        case .FKP:
            return "Falkland Islands"
        case .KGS:
            return "Kyrgyzstan"
        case .MNT:
            return "Mongolia"
        case .THB:
            return "Thailand"
        case .RWF:
            return "Rwanda"
        case .MXN:
            return "Mexico"
        case .MGA:
            return "Madagascar"
        case .MUR:
            return "Mauritius"
        case .ZMW:
            return "Zambia"
        case .SLL:
            return "Country"
        case .INR:
            return "Bhutan"
        }
    }
    
    var flagName : String {
        switch self {
            
        case .KYD:
            return "Cayman Islands"
        case .JPY:
            return "Japan"
        case .SOS:
            return "Somalia"
        case .CAD:
            return "Canada"
        case .HN:
            return "Honduras"
        case .FJD:
            return "Fiji"
        case .MZN:
            return "Mozambique"
        case .MDL:
            return "Moldova"
        case .QAR:
            return "Qatar"
        case .UGX:
            return "Uganda"
        case .IRR:
            return "Iran"
        case .STN:
            return "São Tomé and Príncipe"
        case .UAH:
            return "Ukraine"
        case .KRW:
            return "Korea South"
        case .CDF:
            return "Congo"
        case .SYP:
            return "Syria"
        case .TVD:
            return "Country"
        case .CHF:
            return "Liechtenstein"
        case .CUP:
            return "Cuba"
        case .KID:
            return "Country"
        case .TZS:
            return "Tanzania"
        case .TOP:
            return "Tonga"
        case .XPF:
            return "French Polynesia"
        case .CLP:
            return "Chile"
        case .PGK:
            return "Papua New Guinea"
        case .EUR:
            return "Andorra"
        case .NIO:
            return "Nicaragua"
        case .ANG:
            return "Curaçao"
        case .ERN:
            return "Eritrea"
        case .NGN:
            return "Nigeria"
        case .BMD:
            return "Bermuda"
        case .KES:
            return "Kenya"
        case .NAD:
            return "Namibia"
        case .CRC:
            return "Costa Rica"
        case .AWG:
            return "Aruba"
        case .PYG:
            return "Paraguay"
        case .MMK:
            return "Myanmar"
        case .SRD:
            return "Suriname"
        case .BGN:
            return "Bulgaria"
        case .MWK:
            return "Malawi"
        case .BYN:
            return "Belarus"
        case .BZD:
            return "Country"
        case .LKR:
            return "Country"
        case .AZN:
            return "Country"
        case .PHP:
            return "Country"
        case .SDG:
            return "Country"
        case .HUF:
            return "Country"
        case .UZS:
            return "Country"
        case .GIP:
            return "Country"
        case .XCD:
            return "Country"
        case .TJS:
            return "Country"
        case .MYR:
            return "Country"
        case .GMD:
            return "Country"
        case .LAK:
            return "Country"
        case .CZK:
            return "Country"
        case .PKR:
            return "Country"
        case .PAB:
            return "Country"
        case .BAM:
            return "Country"
        case .ISK:
            return "Country"
        case .GHS:
            return "Country"
        case .TTD:
            return "Country"
        case .BND:
            return "Country"
        case .YER:
            return "Country"
        case .PLN:
            return "Country"
        case .XOF:
            return "Country"
        case .AFN:
            return "Country"
        case .IMP:
            return "Country"
        case .LSL:
            return "Country"
        case .MRU:
            return "Country"
        case .SHP:
            return "Country"
        case .AED:
            return "Country"
        case .DJF:
            return "Country"
        case .GNF:
            return "Country"
        case .VND:
            return "Country"
        case .ILS:
            return "Country"
        case .WST:
            return "Country"
        case .BDT:
            return "Country"
        case .LBP:
            return "Country"
        case .KMF:
            return "Country"
        case .ZWL:
            return "Country"
        case .RSD:
            return "Country"
        case .GTQ:
            return "Country"
        case .SZL:
            return "Country"
        case .TWD:
            return "Country"
        case .XAF:
            return "Country"
        case .ZAR:
            return "Country"
        case .SCR:
            return "Country"
        case .AUD:
            return "Country"
        case .BTN:
            return "Country"
        case .DOP:
            return "Country"
        case .ETB:
            return "Country"
        case .LRD:
            return "Country"
        case .GEL:
            return "Country"
        case .FOK:
            return "Country"
        case .DKK:
            return "Country"
        case .BBD:
            return "Country"
        case .NPR:
            return "Country"
        case .BOB:
            return "Country"
        case .BHD:
            return "Country"
        case .AOA:
            return "Country"
        case .SSP:
            return "Country"
        case .BIF:
            return "Country"
        case .AMD:
            return "Country"
        case .BWP:
            return "Country"
        case .ALL:
            return "Country"
        case .KHR:
            return "Country"
        case .GGP:
            return "Country"
        case .IDR:
            return "Country"
        case .RON:
            return "Country"
        case .SAR:
            return "Country"
        case .JOD:
            return "Country"
        case .SGD:
            return "Country"
        case .JEP:
            return "Country"
        case .KZT:
            return "Country"
        case .XDR:
            return "Country"
        case .CNY:
            return "Country"
        case .SBD:
            return "Country"
        case .NZD:
            return "Country"
        case .BRL:
            return "Country"
        case .OMR:
            return "Country"
        case .MOP:
            return "Country"
        case .CVE:
            return "Country"
        case .RUB:
            return "Country"
        case .KWD:
            return "Country"
        case .GBP:
            return "Country"
        case .LYD:
            return "Country"
        case .MKD:
            return "Country"
        case .NOK:
            return "Country"
        case .JMD:
            return "Country"
        case .COP:
            return "Country"
        case .DZD:
            return "Country"
        case .ARS:
            return "Country"
        case .HRK:
            return "Country"
        case .SEK:
            return "Country"
        case .TND:
            return "Country"
        case .IQD:
            return "Country"
        case .HKD:
            return "Country"
        case .MVR:
            return "Country"
        case .MAD:
            return "Country"
        case .PEN:
            return "Country"
        case .EGP:
            return "Country"
        case .TMT:
            return "Country"
        case .SLE:
            return "Country"
        case .BSD:
            return "Country"
        case .VUV:
            return "Country"
        case .GYD:
            return "Country"
        case .VES:
            return "Country"
        case .UYU:
            return "Country"
        case .TRY:
            return "Country"
        case .HTG:
            return "Country"
        case .USD:
            return "Country"
        case .FKP:
            return "Country"
        case .KGS:
            return "Country"
        case .MNT:
            return "Country"
        case .THB:
            return "Country"
        case .RWF:
            return "Country"
        case .MXN:
            return "Country"
        case .MGA:
            return "Country"
        case .MUR:
            return "Country"
        case .ZMW:
            return "Country"
        case .SLL:
            return "Country"
        case .INR:
            return "Country"
        }
    }
}
